# Generated by Django 3.1.3 on 2020-11-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('PlayerId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Slug', models.SlugField(unique=True)),
                ('PlayerFirstName', models.CharField(max_length=10, verbose_name='Имя игрока')),
                ('PlayerLastName', models.CharField(max_length=20, verbose_name='Фамилия игрока')),
                ('PlayerEmail', models.EmailField(max_length=254, unique=True, verbose_name='e-mail Имя игрока')),
                ('PlayerPic', models.ImageField(upload_to='', verbose_name='Фото игрока')),
                ('PlayerBirth', models.DateField(verbose_name='Дата рождения игрока')),
                ('PlayerRating', models.PositiveIntegerField(verbose_name='Рейтинг игрока')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('TournamentId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Slug', models.SlugField(unique=True)),
                ('TournamentName', models.CharField(max_length=500, verbose_name='Название турнира')),
                ('TournamentDate', models.DateTimeField(verbose_name='Дата и время проведения турнира')),
                ('TournamentDescription', models.TextField(verbose_name='Описание турнира')),
                ('TournamentStatus', models.CharField(choices=[('planned', 'Запланирован'), ('cancelled', 'Отменен'), ('progress', 'Текущий'), ('done', 'Завершен')], default='planned', max_length=12)),
            ],
        ),
    ]
